= Gizz Tapes

A Open Source King Gizzard and the Lizard Wizard music player, utilizing the
https://tapes.kglw.net/[Gizz Tapes] API for streaming audio.

== Building

Standard gradle commands. 

`./gradlew installDebug` to install the test build
`./gradlew build` will build release and debug builds as well as run all checks.

=== Build Scans

Add to gradle.properties with `systemProp.GIZZ_TAPES_ACCEPT_BUILD_SCAN_AGREEMENT=yes`
to enable build scans on every build.

== License

....
Copyright 2024 Andrew Reitz

Licensed to the Apache Software Foundation (ASF) under one or more contributor
license agreements.  See the NOTICE file distributed with this work for
additional information regarding copyright ownership.  The ASF licenses this
file to you under the Apache License, Version 2.0 (the "License"); you may not
use this file except in compliance with the License.  You may obtain a copy of
the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
License for the specific language governing permissions and limitations under
the License.
....
