platform :ios, '15.3'
use_frameworks!

target 'iosApp' do
  pod 'composeApp', :path => '../composeApp'
  pod 'FirebaseCrashlytics'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.3'
    end
  end
end