default_platform(:android)

platform :ios do
  desc 'Build and submit to App Store for review'
  lane :release do
    ensure_git_branch(branch: 'main')
    setup_ci
    api_key = app_store_connect_api_key(
      key_id: ENV['ASC_KEY_ID'],
      issuer_id: ENV['ASC_ISSUER_ID'],
      key_content: ENV['ASC_KEY_CONTENT'],
      is_key_content_base64: true
    )
    match(
      type: 'appstore',
      readonly: true,
      api_key: api_key
    )
    current_build = latest_testflight_build_number(
      api_key: api_key,
      app_identifier: 'gizz.tapes.GizzTapes'
    )
    increment_build_number(
      build_number: current_build + 1,
      xcodeproj: 'iosApp/iosApp.xcodeproj'
    )
    update_code_signing_settings(
      use_automatic_signing: false,
      path: 'iosApp/iosApp.xcodeproj',
      team_id: 'QHJAD8Z2WL',
      bundle_identifier: 'gizz.tapes.GizzTapes',
      code_sign_identity: 'Apple Distribution',
      profile_name: 'match AppStore gizz.tapes.GizzTapes'
    )
    build_app(
      project: 'iosApp/iosApp.xcodeproj',
      scheme: 'iosApp',
      configuration: 'Release',
      export_method: 'app-store'
    )
    upload_to_app_store(
      api_key: api_key,
      submit_for_review: true,
      automatic_release: false,
      skip_waiting_for_build_processing: true
    )
  end

  desc 'Build and upload to TestFlight'
  lane :beta do
    setup_ci
    api_key = app_store_connect_api_key(
      key_id: ENV['ASC_KEY_ID'],
      issuer_id: ENV['ASC_ISSUER_ID'],
      key_content: ENV['ASC_KEY_CONTENT'],
      is_key_content_base64: true
    )
    match(
      type: 'appstore',
      readonly: true,
      api_key: api_key
    )
    current_build = latest_testflight_build_number(
      api_key: api_key,
      app_identifier: 'gizz.tapes.GizzTapes'
    )
    increment_build_number(
      build_number: current_build + 1,
      xcodeproj: 'iosApp/iosApp.xcodeproj'
    )
    update_code_signing_settings(
      use_automatic_signing: false,
      path: 'iosApp/iosApp.xcodeproj',
      team_id: 'QHJAD8Z2WL',
      bundle_identifier: 'gizz.tapes.GizzTapes',
      code_sign_identity: 'Apple Distribution',
      profile_name: 'match AppStore gizz.tapes.GizzTapes'
    )
    build_app(
      project: 'iosApp/iosApp.xcodeproj',
      scheme: 'iosApp',
      configuration: 'Release',
      export_method: 'app-store'
    )
    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end

def update_gradle_properties(properties)
  gradle_properties_lines = File.readlines('../gradle.properties')

  gradle_properties_lines = gradle_properties_lines.map do |line|
    if line.strip.start_with?("#") || line.strip.empty?
      line
    else
      key, value = line.strip.split("=", 2)
      if properties.key?(key)
        "#{key}=#{properties[key]}\n"
      else
        line
      end
    end
  end

  File.write('../gradle.properties', gradle_properties_lines.join)
end

platform :android do

  desc 'Publish a new build to open testing on Play Store'
  lane :beta do
    gradle(
      task: 'bundle',
      flavor: 'full',
      build_type: 'Release'
    )
    upload_to_play_store(
      track: 'beta',
      skip_upload_apk: true,
      aab: lane_context[:GRADLE_AAB_OUTPUT_PATH]
    )
  end

  desc 'Release app to production and create github release'
  lane :release do
    # make sure we only publish on main
    ensure_git_branch(branch: 'main')

    # Read properties from gradle.properties
    properties = {}
    gradle_properties_lines = File.readlines('../gradle.properties')
    gradle_properties_lines.each do |line|
      # Skip empty lines and comments
      next if line.strip.empty? || line.strip.start_with?("#")

      # Split into key and value
      key, value = line.strip.split("=", 2)
      properties[key] = value.strip if key && value
    end

    current_version = properties['gizz.tapes.defaultBuildNumber'].to_i
    version_name = properties['gizz.tapes.versionName']

    keys_properties = {}
    File.foreach('../keys/keys.properties') do |line|
      next if line.strip.start_with?("#") || line.strip.empty?

      key, value = line.strip.split("=", 2)
      keys_properties[key] = value.strip if key && value
    end

    github_token = keys_properties['github_token']

    content = File.read('../CHANGELOG.adoc')
    sections = content.split(/^== .*/)
    description = sections[1].strip

    # write new version and commit and push it
    update_gradle_properties(properties)
    git_commit(path: './gradle.properties', message: 'Version Bump')
    push_to_git_remote()

    gradle(
      task: 'build',
      properties: {
        'gizz.tapes.buildNumber' => current_version
      }
    )

    upload_to_play_store(
      track: 'production',
      skip_upload_apk: true,
      aab: lane_context[:GRADLE_AAB_OUTPUT_PATH]
    )

    # Find all .apk and .aab files in the specified directories
    apk_files = Dir.glob('androidApp/build/outputs/apk/*/release/*.apk')
    aab_files = Dir.glob('androidApp/build/outputs/bundle/*Release/*.aab')

    # Combine all files into a single array
    upload_assets = apk_files + aab_files

    if upload_assets.empty?
      UI.error("No APK or AAB files found to upload!")
    else
      UI.success("Found the following files to upload: #{upload_assets.join(', ')}")
    end

    # Sign all assets with GPG and include .asc files in the release
    asc_files = []
    upload_assets.each do |file|
      sh("gpg --batch --yes --armor --detach-sign \"#{file}\"")
      asc_files << "#{file}.asc"
    end
    upload_assets = upload_assets + asc_files

    set_github_release(
      repository_name: 'Ghost-Applications/gizz-tapes',
      api_token: keys_properties['github_token'],
      upload_assets: upload_assets,
      name: version_name,
      tag_name: version_name,
      description: description
    )

    next_release_name = prompt(
      text: "Enter the name of the next release:"
    )

    # Find the first occurrence of `==` and insert text after it
    updated_content = content.sub(/^== .*/) do |match|
      "#{match} #{Date.today.iso8601}"
    end

    # Insert the new header after the title (the first line starting with `=`)
    updated_content = updated_content.sub(/^= .*/) do |match|
      "#{match}\n\n== #{next_release_name}"
    end

    # Write the updated content back to the file
    File.write('../CHANGELOG.adoc', updated_content)

    properties['gizz.tapes.versionName'] = next_release_name.split.join("")
    properties['gizz.tapes.defaultBuildNumber'] = current_version + 1
    update_gradle_properties(properties)
  end
end
